namespace PFramework
{
    public enum GameEvent
    {
        LevelStart,
        LevelComplete,
        LevelFail,
        SelectBrush,
        SelectPaint,
        Slider,
        ChangeStep,
        FillDone,
        SelectNail,
        ChangeMask,
        SelectPattern,
        SelectColor,
        SelectSticker,
        SelectIcon,
        HandUp,
        HandDown,
        HomeHandDown,
        HomeHandUp,
        ChangeHandBG,
        FishishNail,
        ScaleCameraDone,
        LockInput,
        SelectUIItem,
        HideLoadingDone,
        ConstructHome,
        Scroll,
        ChangeBG,
        ShowUI,
        InitGameplayType,
        ScaleNailDone,
        FirstHomeMove,
        Tutorial
    }
}